<h3>Novo Livro</h3>
<br />
<?php
$form=$this->form;

$form->setAttribute('action', $this->url('livraria-admin',array('controller'=>'livros','action'=>'new')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get("id"));
echo '<div class="form-group">';
echo $this->formRow($form->get("nome"));
echo "</div>";
echo '<div class="form-group">';
echo $this->formRow($form->get("categoria"));
echo "</div>";
echo '<div class="form-group">'; 
echo $this->formRow($form->get("autor"));
echo "</div>";
echo '<div class="form-group">';
echo $this->formRow($form->get("isbn"));
echo "</div>";
echo '<div class="form-group">';
echo $this->formRow($form->get("valor"));
echo "</div>";
echo '<div class="form-group">';
echo $this->formSubmit($form->get("submit"));
echo $this->form()->closeTag();



?>
