<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

            <div class="row-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home-livraria') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Bom Lugar"/>&nbsp;<?php echo 'Bom Lugar'; ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home-livraria') ?>">Home</a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home-livraria') ?>">Contato</a></li>
                        <?php //if ($this->UserIdentity('LivrariaAdmin')): ?>                
                            <li class="active"><a href="<?php echo $this->url('livraria-admin', array('controller' => 'categorias')) ?>">Categorias</a></li>
                            <li class="active"><a href="<?php echo $this->url('livraria-admin', array('controller' => 'livros')) ?>">Livros</a></li>
                            <li class="active"><a href="<?php echo $this->url('livraria-admin', array('controller' => 'users')) ?>">Users</a></li>
                            <li class="active"><a href="<?php echo $this->url('livraria-admin-logout') ?>">Logout</a></li>
                        <?php //endif; ?>
                    </ul>

                </div><!--/.nav-collapse -->

            </div>

        </nav>
        <div class="container-fluid">        


            <div class="col-sm-2 col-md-2 " style="height: 100%;">         
                <form name="buscar">
                    <input type="text" class="form-control" placeholder="Pesquisar"><br />
                    <select class="form-control" name="definicao">
                        <option value="apartamento">Apartamento</option>
                        <option value="casa">Apartamento</option>
                        <option value="chacara">Chacara</option>
                        <option value="sala_comercial">Sala Comercial</option>                    
                    </select><br />
                    <select id="tipo" class="form-control" name="tipo">
                        <option value="aluguel">Aluguel</option>
                        <option value="venda">Venda</option>
                    </select><br />
                    <button type="submit" value="Pesquisar" class="btn btn-default">
                        <span class="glyphicon glyphicon-search">&nbsp;Pesquisar</span>
                    </button>
                </form>
                <br />
                <fieldset>
                    <form name="buscar">

                        <legend>Acesso Restrito</legend>
                        <input type="text" placeholder="Usuário" class="form-control"><br>
                        <input type="password" placeholder="Senha" class="form-control"><br>
                        <input type="submit" value="entrar" class="btn btn-success">
                    </form>
                </fieldset>
            </div>
            <div class="col-sm-9 col-md-9">
                <table class="table table-striped table-hover" >
                    <tr>
                        <td>  <img style="width: 200px;"src="http://localhost/cursozf/public/img/casa1.jpg" /></td>
                        <td><b> Apartamento - Recanto das Emas</b> <br>Preço : 200,000 <br>Endereço: Qd 205 Cj 10 Cs 07</td>
                        <td>Imobiliária Recanto<br><span class="glyphicon glyphicon-earphone"></span> (61) 91740743</td>
                        <td>

                            <button type="submit" value="Pesquisar" class="btn btn-primary">
                                <span class="glyphicon glyphicon-camera"></span>
                            </button></td>
                    </tr>
                    <tr>
                        <td>  <img style="width: 200px;"src="http://localhost/cursozf/public/img/casa1.jpg" /></td>
                        <td><b> Apartamento - Recanto das Emas</b> <br>Preço : 200,000 <br>Endereço: Qd 205 Cj 10 Cs 07</td>
                        <td>Imobiliária Recanto<br><span class="glyphicon glyphicon-earphone"></span> (61) 91740743</td>
                        <td>

                            <button type="submit" value="Pesquisar" class="btn btn-primary">
                                <span class="glyphicon glyphicon-camera"></span>
                            </button></td>
                    </tr>
                    <tr>
                        <td>  <img style="width: 200px;"src="http://localhost/cursozf/public/img/casa1.jpg" /></td>
                        <td><b> Apartamento - Recanto das Emas</b> <br>Preço : 200,000 <br>Endereço: Qd 205 Cj 10 Cs 07</td>
                        <td>Imobiliária Recanto<br><span class="glyphicon glyphicon-earphone"></span> (61) 91740743</td>
                        <td>

                            <button type="submit" value="Pesquisar" class="btn btn-primary">
                                <span class="glyphicon glyphicon-camera"></span>
                            </button></td>
                    </tr>

                </table>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
